version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      # Persist data on disk
      - /home/tamerlan/docker/elk/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
      - "2055:2055/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
        context: filebeat/
    volumes:
        - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
        # Logs are on host machine not in docker
        # TODO: move nginx to docker!
        - /var/log/nginx/:/var/log/nginx/:ro
        - /var/log/named/:/var/log/named/:ro
    networks:
        - elk
    depends_on:
        - kibana
        - logstash

networks:
  elk:
    driver: bridge
